# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configs are located in `ygo-fabrica/config.toml`,
#  check that file to see possible settings.

[expansion.KamenRider]
default = true
recipe = ["cards/sets.toml", "cards/cards.toml", "cards/macro.toml"]

[gamedir.KamenRider]
path = "/run/media/monyarm/Windows 7/ProjectIgnis/"

[picset.EDOPro]
mode = 'proxy'
size = '512x'
ext = 'png'
year = 2020
author = 'monyarm'
field = true