MAKEFLAGS += --no-builtin-rules
MAKEFLAGS += --no-builtin-variables
MAKEFLAGS += -j -l $(shell nproc)

SHELL := $(shell which zsh) -o extendedglob -o kshglob

# Shared recipe files included in every expansion
shared := cards/sets.toml cards/macro.toml
# Card-specific tomls (everything except shared files)
card_data    := $(filter-out $(shared),$(wildcard cards/*.toml))
card_names   := $(basename $(notdir $(card_data)))
cdbs         := $(addprefix expansions/,$(addsuffix .cdb,$(card_names)))
compose_stamps := $(addprefix .deps/.stamp_,$(card_names))
dep_files    := $(addprefix .deps/,$(addsuffix .d,$(card_names)))

.SECONDARY: $(cdbs)
.DEFAULT_GOAL := default
.PHONY: default install clean uninstall

# Resolve all artwork files for ids declared in a given card TOML.
get_img = $(shell awk -F= '/^[[:space:]]*id[[:space:]]*=/{gsub(/[[:space:]]/, "", $$2); print $$2}' $(1) | while read -r id; do print -r -- artwork/$$id.*(N); done)

-include $(dep_files)

default: $(compose_stamps)

config.toml: $(card_data) $(shared)
	@{ \
		echo "# Auto-generated by: make config.toml"; \
		echo "# Use this to define local configurations for your project."; \
		echo; \
		for f in $(sort $(card_data)); do \
			name=$${f#cards/}; \
			name=$${name%.toml}; \
			echo "[expansion.$${name}]"; \
			echo "default = true"; \
			echo "recipe = ['cards/sets.toml', 'cards/macro.toml', 'cards/$${name}.toml']"; \
			echo; \
		done; \
		echo "[picset.proxy]"; \
		echo "mode = 'proxy'"; \
		echo "size = '512x'"; \
		echo "ext = 'png'"; \
		echo "year = $$(date +%Y)"; \
		echo "field = true"; \
	} > $@

# Step A: data build only (safe to run in parallel).
expansions/%.cdb: cards/%.toml $(shared) config.toml | expansions
	ygofab make $* > /dev/null

# Sidecar dependency files map composition stamps to concrete artwork files.
# The pattern stem % is the card name (e.g. "hero").
.deps/%.d: cards/%.toml | .deps
	@{ \
		printf ".deps/.stamp_%s: %s" "$*" "$<"; \
		for img in $(call get_img,$<); do printf " %s" "$$img"; done; \
		printf "\n"; \
	} > "$@"

.deps expansions:
	mkdir -p $@

# Step B: image composition (depends on CDB and sidecar-tracked artwork files).
# .deps/%.d is order-only: its mtime alone does not trigger recompose;
# actual rebuild triggers come from the CDB and artwork prereqs injected by the sidecar.
.deps/.stamp_%: expansions/%.cdb | .deps/%.d
	flock /tmp/ygofab.lock -c "ygofab compose -p proxy -e $*"
	@touch $@

clean:
	rm -f $(cdbs)
	rm -f $(compose_stamps) $(dep_files)
	rm -f pics/proxy/{,field/}*.{png,jpg}
	rm -f config.toml

