[card.kr-joker]
id = 19710001
name = "Kamen Rider Joker"
attribute = "dark"
level = 4
type = "monster normal"
race = "warrior"
set = "masked-hero destiny-hero hero kamen-rider"
flavor-text = '''
Saa, omae no tsumi o kazoero.



(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)'''
atk = 2000
def = 1800

[card.kr-wizard]
id = 19710002
name = "Kamen Rider Wizard"
attribute = "fire"
level = 7
pendulum-scale = 5
pendulum-effect = '''
All face-up spellcaster-type monsters you control gain 100 ATK for each spell card on the field..'''
type = "monster effect pendulum"
race = "spellcaster"
set = "masked-hero destiny-hero hero kamen-rider"
effect = '''
(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)
Kamen Rider Wizard is also treated as a Warrior-Type monster.'''
atk = 2500
def = 1500


[card.kr-wizard2]
id = 197100021
allias= 19710002
name = "Kamen Rider Wizard"
attribute = "fire"
level = 7
pendulum-scale = 5
pendulum-effect = '''
All face-up spellcaster-type monsters you control gain 100 ATK for each spell card on the field..'''
type = "monster effect pendulum"
race = "spellcaster"
set = "masked-hero destiny-hero hero kamen-rider"
effect = '''
(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)
Kamen Rider Wizard is also treated as a Warrior-Type monster.'''
atk = 2500
def = 1500