[card.kr-joker]
id = 19710001
name = "Kamen Rider Joker"
attribute = "dark"
level = 4
type = "monster normal"
race = "warrior"
set = "kamen-rider masked-hero destiny-hero"
flavor-text = '''
Saa, omae no tsumi o kazoero.



(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)'''
atk = 2000
def = 1800

[card.kr-wizard]
id = 19710002
name = "Kamen Rider Wizard"
attribute = "fire"
level = 7
pendulum-scale = 5
pendulum-effect = '''${WIZARDPEFFECT}'''
type = "monster effect pendulum"
race = "spellcaster"
set = "kamen-rider masked-hero elemental-hero"
effect = '''${WIZARDEFFECT}'''
atk = 2500
def = 1500


[card.kr-wizard2]
id = 197100021
alias= 19710002
name = "Kamen Rider Wizard"
attribute = "fire"
level = 7
pendulum-scale = 5
pendulum-effect = '''${WIZARDPEFFECT}'''
type = "monster effect pendulum"
race = "spellcaster"
set = "kamen-rider masked-hero elemental-hero "
effect = '''${WIZARDEFFECT}'''
atk = 2500
def = 1500


[card.kr-wizard3]
id = 197100022
alias= 19710002
name = "Kamen Rider Wizard"
attribute = "fire"
level = 7
pendulum-scale = 5
pendulum-effect = '''${WIZARDPEFFECT}'''
type = "monster effect pendulum"
race = "spellcaster"
set = "kamen-rider masked-hero elemental-hero"
effect = '''${WIZARDEFFECT}'''
atk = 2500
def = 1500



[card.kr-wizard-prependulum]
id = 19710012
alias= 19710002
name = "Kamen Rider Wizard (Pre-Pendulum)"
attribute = "fire"
level = 7
type = "monster effect"
race = "spellcaster"
set = "kamen-rider masked-hero elemental-hero"
effect = '''${WIZARDEFFECT}'''
atk = 2500
def = 1500


[card.kr-wizard2-prependulum]
id = 197100121
alias= 19710002
name = "Kamen Rider Wizard (Pre-Pendulum)"
attribute = "fire"
level = 7
type = "monster effect"
race = "spellcaster"
set = "kamen-rider masked-hero elemental-hero "
effect = '''${WIZARDEFFECT}'''
atk = 2500
def = 1500


[card.kr-wizard3-prenepndulum]
id = 197100122
alias= 19710002
name = "Kamen Rider Wizard (Pre-Pendulum)"
attribute = "fire"
level = 7
type = "monster effect"
race = "spellcaster"
set = "kamen-rider masked-hero elemental-hero"
effect = '''${WIZARDEFFECT}'''
atk = 2500
def = 1500

[card.kr-hibiki]
id = 19710003
name = "Kamen Rider Hibiki"
attribute = "dark"
level = 7
type = "monster effect ritual"
race = "fiend"
set = "kamen-rider masked-hero destiny-hero"
effect = '''
Must be Ritual Summoned, and cannot be Special Summoned by other ways. 
Kamen Rider Hibiki is also treated as a Warrior-Type monster.

Kamen Rider Hibiki gains 1300 ATK when batting a level 8 or higher monster.
Kamen Rider Hibiki gains 1300 ATK when batting a rank 5 or higher monster.
Kamen Rider Hibiki gains 1300 ATK when batting a link 3 or higher monster.

(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)'''
atk = 2700
def = 2000


[card.ongeki-henshin]
id = 19710004
name = "Ongeki Henshin"
attribute= "spell"
type = "spell ritual" 
effect = '''
This card can be used to Ritual Summon any "Kamen Rider" Ritual Monster. You must also Tribute monsters from your hand or field, whose total Levels equal the Level of the "Kamen Rider" Ritual Monster you Ritual Summon.'''



[card.dr-rey]
id = 19710005
name = "Dark Rider Rey"
attribute = "water"
rank = 4
type = "monster effect xyz"
race = "aqua"
set = "dark-rider masked-hero evil-hero"
effect = '''
2 or more (max. 5) level 4 WATER monsters.
Dark Rider Rey is also treated as a Warrior-Type monster.
Once per turn: You can detach 1 Xyz Material from this card to target 1 monster your opponent controls or is in their Graveyard; banish that target. This card gains effects based on the number of Xyz Materials attached to it.
● 3 or more: This card gains 100 ATK and DEF for each Xyz Material attached to it.
● 4 or more: This card gains 200 ATK and DEF for each Xyz Material attached to it.
● 5: This card cannot be destroyed by card effects. 
(This card is always treated as a "Masked HERO", "Evil HERO" and "Kamen Rider" monster.)'''
atk = 2500
def = 2000


[card.kr-kiva]
id = 19710006
name = "Kamen Rider Kiva"
attribute = "dark"
level = 4
type = "monster effect"
race = "zombie"
set = "kamen-rider masked-hero destiny-hero"
effect = '''
Kamen Rider Kiva is also trated as a Warrior-Type monster.
When this card deals battle damage to your opponent, you gain lifepoints equal to half the damage dealt.
This card deals piercing damage.
(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)'''
atk = 1200
def = 900


[card.kr-kiva2]
id = 197100061
alias = 19710006
name = "Kamen Rider Kiva"
attribute = "dark"
level = 4
type = "monster effect"
race = "zombie"
set = "kamen-rider masked-hero destiny-hero"
effect = '''
Kamen Rider Kiva is also trated as a Warrior-Type monster.
When this card deals battle damage to your opponent, you gain lifepoints equal to half the damage dealt.
This card deals piercing damage.
(This card is always treated as both a "Masked HERO" and "Destiny HERO" monster.)'''
atk = 1200
def = 900

[card.kr-shinobi]
id = 19710007
name = "Kamen Rider Shinobi"
attribute = "dark"
level = 3
type = "monster effect"
race = "warrior"
set = "kamen-rider masked-hero destiny-hero ninja"
effect = '''
This card can make a second attack during each Battle Phase.

(This card is always treated as a "Masked HERO", "Destiny HERO" and "Ninja" monster.)'''
atk = 1200
def = 800



[card.rider-war]
id = 19710008
name = "Rider War"
type = "spell field"
effect = '''
"Masked HERO" and "Kaijin" monsters gain 500 ATK.
Once per turn, when an "Masked HERO" monster is destroyed by battle or card effect and sent to the GY: You can Special Summon 1 "Masked HERO" monster from your Deck with a Level less than or equal to that "Masked HERO" monster in the GY. 
'''


[card.kr-decade]
id = 19710009
name = "Kamen Rider Decade"
attribute = "dark"
level = 7
pendulum-scale = 3
pendulum-effect = '''If you control "Kamen Rider Diend", you can special summon this card from your pendulum zone.'''
type = "monster effect pendulum"
race = "warrior"
set = "kamen-rider destiny-hero masked-hero"
effect = '''${DECADEEFFECT}'''
atk = 2500
def = 2000

[card.kr-diend]
id = 19710010
name = "Kamen Rider Diend"
attribute = "dark"
level = 8
pendulum-scale = 8
pendulum-effect = '''If you control "Kamen Rider Decade", you can special summon this card from your pendulum zone.'''
type = "monster effect pendulum"
race = "warrior"
set = "kamen-rider destiny-hero masked-hero"
effect = '''${DIENDEFFECT}'''
atk = 1500
def = 2000



[card.kr-decade-prependulum]
id = 19710011
name = "Kamen Rider Decade (Pre-Pendulum)"
attribute = "dark"
level = 7
type = "monster effect"
race = "warrior"
set = "kamen-rider destiny-hero masked-hero"
effect = '''${DECADEEFFECT}'''
atk = 2500
def = 2000

[card.kr-diend-prependulum]
id = 19710013
name = "Kamen Rider Diend (Pre-Pendulum)"
attribute = "dark"
level = 8
type = "monster effect"
race = "warrior"
set = "kamen-rider destiny-hero masked-hero"
effect = '''${DIENDEFFECT}'''
atk = 1500
def = 2000

[card.kamen-ride-decade]
id = 19710014
name = "Kamen Ride - Decade"
type = "spell quickplay"
effect = '''
Tribute a face up "Masked HERO" monster. Special Summon "Kamen Rider Decade" from your hand, deck or GY.
You can only activate "Kamen Ride - Decade" once per turn.'''