[set.kamen-rider]
code = 0x619
name = "Kamen Rider"

[set.dark-rider]
code = 0xa619
name = "Dark Rider"

[set.armored-rider]
code = 0xb619
name = "Armored Rider"

[set.kaijin]
code = 0x620
name = "Kaijin"

[set.genesis-rider]
code = 0xc619
name = "Genesis Rider"

[set.shiftcar]
code = 0x621
name = "shiftcar"

[set.elemental-hero]
code = 0x3008
name = "Elemental HERO"

[set.hero]
code = 0x8
name = "HERO"

[set.vision-hero]
code = 0x5008
name = "Vision HERO"

[set.evil-hero]
code = 0x6008
name = "Evil HERO"

[set.masked-hero]
code = 0xa008
name = "Masked HERO"

[set.destiny-hero]
code = 0xc008
name = "Destiny HERO"

[set.ninja]
code = 0x2b
name = "Ninja"