[set.kamen-rider]
code = 0x619
name = "Kamen Rider"

[set.sentai]
code = 0x719
name = "Sentai"

[set.sentai-ally]
code = 0x722
name = "Sentai Ally"

[set.dark-rider]
code = 0xa619
name = "Dark Rider"

[set.another-rider]
code = 0xb619
name = "Another Rider"

[set.kaijin]
code = 0x620
name = "Kaijin"


[set.rider-gadget]
code = 0x621
name = "Rider Gadget"

[set.rider-ally]
code = 0x622
name = "Rider Ally"

[set.shiftcar]
code = 0xa621
name = "Shiftcar"

[set.elemental-hero]
code = 0x3008
name = "Elemental HERO"

[set.hero]
code = 0x8
name = "HERO"

[set.vision-hero]
code = 0x5008
name = "Vision HERO"

[set.evil-hero]
code = 0x6008
name = "Evil HERO"

[set.masked-hero]
code = 0xa008
name = "Masked HERO"

[set.destiny-hero]
code = 0xc008
name = "Destiny HERO"

[set.ninja]
code = 0x2b
name = "Ninja"